filetype plugin indent on
syntax on

colorscheme desert

set title
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set hlsearch

set number
set number relativenumber

augroup numbertoggle
  autocmd!
  autocmd BufEnter,FocusGained,InsertLeave * set relativenumber
  autocmd BufLeave,FocusLost,InsertEnter   * set norelativenumber
augroup END
